### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by vmarcosp** [RodrigoWP/react-password-strength#3]
I think that would be interesting have a way to add messages in other languages. Examples: English, Mandarin, etc. What do u think ?

**Comment by vmarcosp** [comment]
What do you think to change the default messages from Portuguese to English?

**Comment by RodrigoWP** [comment]
Hi @vmarcosp. This a sweet idea! 

Actually, I was thinking of taking out this responsibility the library and enable to pass an array of message like as: ['message1, message2', 'message3'] following the strength order

**Comment by vmarcosp** [comment]
Hi, yeah!
My idea is enable to pass an object with prop as level and value as message, like this:

{ 0: 'Very Weak' }

Following the model used by your library.

**Comment by RodrigoWP** [comment]
Perfect! :D

**Comment by vmarcosp** [comment]
I sent a PR about that https://github.com/RodrigoWP/react-password-strength/pull/7
